LOGGER_ENABLE_FILE_LOGGER: true
LOGGER_ENABLE_KAFKA_LOGGER: false
LOGGER_ENABLE_CONSOLE_LOGGER: false
LOGGER_LEVEL: -1
LOGGER_FILE_NAME: ./app.log
LOGGER_FILE_MAX_SIZE: 100
LOGGER_FILE_MAX_AGE: 10
LOGGER_FILE_MAX_BACKUPS: 10
LOGGER_FILE_LOCAL_TIME: true
LOGGER_FILE_COMPRESS: true
LOGGER_KAFKA_ADDRESS: localhost:9092
LOGGER_KAFKA_TOPIC: simple_api
