#日志配置
LOGGER_ENABLE_FILE_LOGGER: false
LOGGER_ENABLE_KAFKA_LOGGER: false
LOGGER_ENABLE_CONSOLE_LOGGER: true
LOGGER_LEVEL: -1
LOGGER_FILE_NAME: ./app.log
LOGGER_FILE_MAX_SIZE: 100
LOGGER_FILE_MAX_AGE: 10
LOGGER_FILE_MAX_BACKUPS: 10
LOGGER_FILE_LOCAL_TIME: true
LOGGER_FILE_COMPRESS: true
LOGGER_KAFKA_ADDRESS: localhost:9092
LOGGER_KAFKA_TOPIC: simple_api
#链路跟踪配置
OPENTRACING_ENABLE: true
JAEGER_SERVICE_NAME: simple_api_tracer
JAEGER_DISABLED:
JAEGER_RPC_METRICS:
JAEGER_TAGS: app=api,env=dev
JAEGER_SAMPLER_TYPE: const
JAEGER_SAMPLER_PARAM: 1
JAEGER_SAMPLER_MANAGER_HOST_PORT:
JAEGER_SAMPLER_MAX_OPERATIONS:
JAEGER_SAMPLER_REFRESH_INTERVAL:
JAEGER_REPORTER_MAX_QUEUE_SIZE:
JAEGER_REPORTER_FLUSH_INTERVAL:
JAEGER_REPORTER_LOG_SPANS:
JAEGER_ENDPOINT:
JAEGER_USER:
JAEGER_PASSWORD:
JAEGER_AGENT_HOST: localhost
JAEGER_AGENT_PORT: 6831
